# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- template: templates/stage-build.yml
  parameters:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
- template: templates/stage-create-db-container.yml
  parameters:
    resourceGroup: 'blogrs'
    container: 'blog-pg-115'
- template: templates/stage-deploy-db-changes.yml
  parameters:
    efcorepath: '../Blog.PostgreSQL.EF/Blog.PostgreSQL.EF.csproj'