# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  dotnetVersion: '5.x'

stages:
- stage: CreateWebArtifact
  displayName: 'Create Web Artifact'
  pool:
    vmImage: ubuntu-latest

  jobs:

  - job: BuildWebApi
    displayName: 'Build Web API Code'
    steps:
    - task: @UseDotNet@2
      displayName: '$(dotnetVersion)'
      inputs:
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Build Web API Project'
      inputs:
        command: 'build'
        arguments: '--no-response --configuration $(buildConfiguration)'
        projects: '$(System.DefaultWorkingDirectory)/**/Blog.Web.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish Project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: 'webProject'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact: drop'
      condition: succeeded()

