parameters:
  resourceGroup: ''
  container: ''

stages:
- stage: CreateDBContainer
  displayName: 'Create DB Container'
  jobs:
  - job: CreateDockerContainer
    displayName: 'Create Docker Container'
    steps:
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create --name ${{ parameters.resourceGroup }} --location southcentralus'
    - task: AzureCLI@2
      displayName: 'Create PostgreSQL Container'
      inputs:
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create --resource-group ${{ parameters.resourceGroup }} --os-type Linux --name ${{ parameters.container }} --image postgres:11.5 --ports 5432 --ip-address Public --dns-name-label ${{ parameters.container }} --environment-variables="POSTGRES_PASSWORD=postgres"'