parameters:
  resourceGroup: ''
  container: ''

stages:
- stage: CreateDBContainer
  displayName: 'Create DB Container'
  jobs:
  - job: CreateDockerContainer
    displayName: 'Create Docker Container'
    steps:
    
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        displayName: 'Create Resource Group'
        azureSubscription: 'Visual Studio Enterprise Subscription(3d5606e1-6371-4322-b08d-b12fc3b3669f)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create --name ${{ parameters.resourceGroup }} --location southcentralus'

    - task: AzureCLI@2
      displayName: 'Create PostgreSQL Container'
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription(3d5606e1-6371-4322-b08d-b12fc3b3669f)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create --resource-group ${{ parameters.resourceGroup }} --os-type Linux --name ${{ parameters.container }} --image postgres:11.5 --ports 5432 --ip-address Public --dns-name-label ${{ parameters.container }} --environment-variables="POSTGRES_PASSWORD=postgres"'

    - task: UseDotNet@2
      displayName: 'Install 3.1 version of .NET Core'
      inputs:
        version: '3.1.x'

    - task: DotNetCoreCLI@2
      displayName: 'Install Entity Framework'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global dotnet-ef'

    - task: Bash@3